In [8]:
import numpy as np

In [10]:
x_np=np.array([1,2,3])
x_np

array([1, 2, 3])

for transpose

In [11]:
x_npt=x_np.T
x_npt

array([1, 2, 3])

for zero vector

In [13]:
x=np.zeros(3)
x

array([0., 0., 0.])

In [1]:
import torch

In [2]:
x_pt=torch.tensor([1,2,3])
x_pt

tensor([1, 2, 3])

In [12]:
import tensorflow as tf

In [7]:
x_tf=tf.Variable([1,2,3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>