In [1]:
import numpy as np

In [2]:
x=np.array([[25,2],[5,26],[3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
x.shape

(3, 2)

In [4]:
x.size

6

In [5]:
x[:,0]

array([25,  5,  3])

In [6]:
x[0,:]

array([25,  2])

In [8]:
x[0:2,0:1]

array([[25],
       [ 5]])

In [9]:
import torch

In [14]:
x_pt=torch.tensor([[25,2],[5,26],[3,7]])
x_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [15]:
import tensorflow as tf

In [16]:
x_tf=tf.Variable([[25,2],[5,26],[3,7]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [17]:
tf.rank(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>